# Generated by Django 4.0.1 on 2022-03-28 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(null=True, verbose_name='Arrival Date (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Departure Date (mm/dd/yyyy)'),
        ),
    ]
