# Generated by Django 4.0.1 on 2022-03-30 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_alter_booking_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Booking Date (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateTimeField(verbose_name='Departure Date (mm/dd/yyyy)'),
        ),
    ]
