# Generated by Django 4.0.1 on 2022-03-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0007_alter_booking_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(verbose_name='Arrival Date (mm/dd/yyyy)'),
        ),
    ]
